# Generated by Django 3.0.3 on 2020-02-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('players', models.ManyToManyField(to='player.PlayerModel')),
            ],
        ),
    ]
