# Generated by Django 3.0.3 on 2020-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_playersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortitionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PlayersModel',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='date',
        ),
        migrations.AddField(
            model_name='sortitionmodel',
            name='teams',
            field=models.ManyToManyField(to='player.TeamModel'),
        ),
    ]
